SELECT        YEAR(dbo.DATA_HISTORY.FECHA) AS ANIO, MONTH(dbo.DATA_HISTORY.FECHA) AS MES, dbo.CLIENTS.COMPNAME AS HOTEL,
                        CAST(AVG(dbo.DATA_HISTORY.PROM_DIA) AS DECIMAL(10, 2)) AS PROM_DIA,
                        cast((CAST(AVG(dbo.DATA_HISTORY.PROM_DIA) AS DECIMAL(10, 2)) / ( SELECT     CAST(AVG(dbo.DATA_HISTORY.PROM_DIA)AS DECIMAL(10, 2))
FROM         dbo.CLIENT_GRUPOS INNER JOIN
                      dbo.GRUPO ON dbo.CLIENT_GRUPOS.IDGRUPO = dbo.GRUPO.IDGRUPO INNER JOIN
                      dbo.DATA_HISTORY ON dbo.CLIENT_GRUPOS.IDCENTRO = dbo.DATA_HISTORY.RASCLIENTID
WHERE     (MONTH(dbo.DATA_HISTORY.FECHA) = '7') AND (YEAR(dbo.DATA_HISTORY.FECHA) = '2015') AND 
                      (dbo.CLIENT_GRUPOS.IDGRUPO = '1')))AS DECIMAL(10, 2)) AS Ind_PROM_DIA, 
						CAST(AVG(dbo.DATA_HISTORY.TASA_OCUPACION) AS DECIMAL(10, 2)) AS TASA_OCUPACION,
						cast((AVG(dbo.DATA_HISTORY.TASA_OCUPACION) /( SELECT AVG(dbo.DATA_HISTORY.TASA_OCUPACION)
FROM         dbo.CLIENT_GRUPOS INNER JOIN
                      dbo.GRUPO ON dbo.CLIENT_GRUPOS.IDGRUPO = dbo.GRUPO.IDGRUPO INNER JOIN
                      dbo.DATA_HISTORY ON dbo.CLIENT_GRUPOS.IDCENTRO = dbo.DATA_HISTORY.RASCLIENTID
WHERE     (MONTH(dbo.DATA_HISTORY.FECHA) = '7') AND (YEAR(dbo.DATA_HISTORY.FECHA) = '2015') AND 
                      (dbo.CLIENT_GRUPOS.IDGRUPO = '1')
) )AS DECIMAL(10, 2)) AS Ind_TASA_OCUPACION, 
                        CAST(AVG(dbo.DATA_HISTORY.TASA_OCUPACION) * AVG(dbo.DATA_HISTORY.PROM_DIA) / 100 AS DECIMAL(10, 2)) AS REVPAR,
                        CAST((CAST(AVG(dbo.DATA_HISTORY.TASA_OCUPACION) * AVG(dbo.DATA_HISTORY.PROM_DIA) / 100 AS DECIMAL(10, 2))/( SELECT     CAST(AVG(dbo.DATA_HISTORY.TASA_OCUPACION) * AVG(dbo.DATA_HISTORY.PROM_DIA) / 100 AS DECIMAL(10, 2))
FROM         dbo.CLIENT_GRUPOS INNER JOIN
                      dbo.GRUPO ON dbo.CLIENT_GRUPOS.IDGRUPO = dbo.GRUPO.IDGRUPO INNER JOIN
                      dbo.DATA_HISTORY ON dbo.CLIENT_GRUPOS.IDCENTRO = dbo.DATA_HISTORY.RASCLIENTID
WHERE     (MONTH(dbo.DATA_HISTORY.FECHA) = '7') AND (YEAR(dbo.DATA_HISTORY.FECHA) = '2015') AND 
                      (dbo.CLIENT_GRUPOS.IDGRUPO = '1')))AS DECIMAL(10, 2)) AS Ind_REVPAR,
						CAST((AVG(dbo.DATA_HISTORY.PROM_DIA) * (CAST((SUM(dbo.DATA_HISTORY.UDS_DIA)*CAST(AVG(dbo.DATA_HISTORY.TASA_OCUPACION) AS DECIMAL(10, 2))/100)AS DECIMAL(10, 2)))) AS DECIMAL(10, 2)) AS REVENUE, 
						RANK() OVER (ORDER BY (CAST((CAST(AVG(dbo.DATA_HISTORY.TASA_OCUPACION) * AVG(dbo.DATA_HISTORY.PROM_DIA) / 100 AS DECIMAL(10, 2))/( SELECT     CAST(AVG(dbo.DATA_HISTORY.TASA_OCUPACION) * AVG(dbo.DATA_HISTORY.PROM_DIA) / 100 AS DECIMAL(10, 2))
FROM         dbo.CLIENT_GRUPOS INNER JOIN
                      dbo.GRUPO ON dbo.CLIENT_GRUPOS.IDGRUPO = dbo.GRUPO.IDGRUPO INNER JOIN
                      dbo.DATA_HISTORY ON dbo.CLIENT_GRUPOS.IDCENTRO = dbo.DATA_HISTORY.RASCLIENTID
WHERE     (MONTH(dbo.DATA_HISTORY.FECHA) = '7') AND (YEAR(dbo.DATA_HISTORY.FECHA) = '2015') AND 
                      (dbo.CLIENT_GRUPOS.IDGRUPO = '1')))AS DECIMAL(10, 2))) DESC) AS RankByRevPar, 
						RANK() OVER (ORDER BY (CAST(AVG(dbo.DATA_HISTORY.TASA_OCUPACION) * AVG(dbo.DATA_HISTORY.PROM_DIA) / 100 AS DECIMAL(10, 2))) DESC) AS RankByIndRevPar, 
						RANK() OVER (ORDER BY (cast((AVG(dbo.DATA_HISTORY.TASA_OCUPACION) /( SELECT AVG(dbo.DATA_HISTORY.TASA_OCUPACION)
FROM         dbo.CLIENT_GRUPOS INNER JOIN
                      dbo.GRUPO ON dbo.CLIENT_GRUPOS.IDGRUPO = dbo.GRUPO.IDGRUPO INNER JOIN
                      dbo.DATA_HISTORY ON dbo.CLIENT_GRUPOS.IDCENTRO = dbo.DATA_HISTORY.RASCLIENTID
WHERE     (MONTH(dbo.DATA_HISTORY.FECHA) = '7') AND (YEAR(dbo.DATA_HISTORY.FECHA) = '2015') AND 
                      (dbo.CLIENT_GRUPOS.IDGRUPO = '1')
) )AS DECIMAL(10, 2))) DESC) AS RankByTO, 
						RANK() OVER (ORDER BY (CAST(AVG(dbo.DATA_HISTORY.TASA_OCUPACION) / 100 AS DECIMAL(10, 2))) DESC) AS RankByIndTO, 
						RANK() OVER (ORDER BY (CAST(AVG(dbo.DATA_HISTORY.PROM_DIA) / 100 AS DECIMAL(10, 2))) DESC) AS RankByTM,
						RANK() OVER (ORDER BY (CAST(AVG(dbo.DATA_HISTORY.PROM_DIA) / 100 AS DECIMAL(10, 2))) DESC) AS RankByIndTM, 
						SUM(dbo.DATA_HISTORY.UDS_DIA) as AV_ROOMS, 
						cast(cast(SUM(dbo.DATA_HISTORY.UDS_DIA) * 100 AS DECIMAL(10, 2)) / (select SUM (UDS_DIA) 
FROM         dbo.CLIENT_GRUPOS INNER JOIN
                      dbo.GRUPO ON dbo.CLIENT_GRUPOS.IDGRUPO = dbo.GRUPO.IDGRUPO INNER JOIN
                      dbo.DATA_HISTORY ON dbo.CLIENT_GRUPOS.IDCENTRO = dbo.DATA_HISTORY.RASCLIENTID
WHERE     (MONTH(dbo.DATA_HISTORY.FECHA) = '7') AND (YEAR(dbo.DATA_HISTORY.FECHA) = '2015') AND 
                      (dbo.CLIENT_GRUPOS.IDGRUPO = '1') ) AS DECIMAL(10, 2)) AS MKSH,
					  CAST((SUM(dbo.DATA_HISTORY.UDS_DIA)*CAST(AVG(dbo.DATA_HISTORY.TASA_OCUPACION) AS DECIMAL(10, 2))/100)AS DECIMAL(10, 2)) as OC_ROOMS,
						CAST(100*(CAST((SUM(dbo.DATA_HISTORY.UDS_DIA)*CAST(AVG(dbo.DATA_HISTORY.TASA_OCUPACION) AS DECIMAL(10, 2))/100)AS DECIMAL(10, 2))/(SELECT (CAST((select (( select (select SUM (UDS_DIA) 
FROM         dbo.CLIENT_GRUPOS INNER JOIN
                      dbo.GRUPO ON dbo.CLIENT_GRUPOS.IDGRUPO = dbo.GRUPO.IDGRUPO INNER JOIN
                      dbo.DATA_HISTORY ON dbo.CLIENT_GRUPOS.IDCENTRO = dbo.DATA_HISTORY.RASCLIENTID
WHERE     (MONTH(dbo.DATA_HISTORY.FECHA) = '7') AND (YEAR(dbo.DATA_HISTORY.FECHA) = '2015') AND 
                      (dbo.CLIENT_GRUPOS.IDGRUPO = '1')) as UDS_DISPONIBLES) * (SELECT     CAST(AVG(MITO) AS DECIMAL(10, 2)) AS TOGEN
FROM (
select (DATA_HISTORY.TASA_OCUPACION) as MITO from DATA_HISTORY where (MONTH(dbo.DATA_HISTORY.FECHA) = '7') AND (YEAR(dbo.DATA_HISTORY.FECHA) = '2015')
 and DATA_HISTORY.RASCLIENTID in ('70606')   
                                                   UNION ALL 
                                                   SELECT     (dbo.DATA_HISTORY.TASA_OCUPACION) 
FROM         dbo.CLIENT_GRUPOS INNER JOIN
                      dbo.GRUPO ON dbo.CLIENT_GRUPOS.IDGRUPO = dbo.GRUPO.IDGRUPO INNER JOIN
                      dbo.DATA_HISTORY ON dbo.CLIENT_GRUPOS.IDCENTRO = dbo.DATA_HISTORY.RASCLIENTID
WHERE     (MONTH(dbo.DATA_HISTORY.FECHA) = '7') AND (YEAR(dbo.DATA_HISTORY.FECHA) = '2015') AND 
                      (dbo.CLIENT_GRUPOS.IDGRUPO = '1')
) S)/100) as UDS_VENDIDAS)AS DECIMAL(10, 2)))))AS DECIMAL(10, 2)) as FRSH
--,
--						(select SUM (UDS_DIA) 
--FROM         dbo.CLIENT_GRUPOS INNER JOIN
--                      dbo.GRUPO ON dbo.CLIENT_GRUPOS.IDGRUPO = dbo.GRUPO.IDGRUPO INNER JOIN
--                      dbo.DATA_HISTORY ON dbo.CLIENT_GRUPOS.IDCENTRO = dbo.DATA_HISTORY.RASCLIENTID
--WHERE     (MONTH(dbo.DATA_HISTORY.FECHA) = '7') AND (YEAR(dbo.DATA_HISTORY.FECHA) = '2015') AND 
--                      (dbo.CLIENT_GRUPOS.IDGRUPO = '1') ) as UDS_DISPONIBLES,
--                      (SELECT (CAST((select (( select (select SUM (UDS_DIA) 
--FROM         dbo.CLIENT_GRUPOS INNER JOIN
--                      dbo.GRUPO ON dbo.CLIENT_GRUPOS.IDGRUPO = dbo.GRUPO.IDGRUPO INNER JOIN
--                      dbo.DATA_HISTORY ON dbo.CLIENT_GRUPOS.IDCENTRO = dbo.DATA_HISTORY.RASCLIENTID
--WHERE     (MONTH(dbo.DATA_HISTORY.FECHA) = '7') AND (YEAR(dbo.DATA_HISTORY.FECHA) = '2015') AND 
--                      (dbo.CLIENT_GRUPOS.IDGRUPO = '1')) as UDS_DISPONIBLES) * (SELECT     CAST(AVG(MITO) AS DECIMAL(10, 2)) AS TOGEN
--FROM (
--select (DATA_HISTORY.TASA_OCUPACION) as MITO from DATA_HISTORY where (MONTH(dbo.DATA_HISTORY.FECHA) = '7') AND (YEAR(dbo.DATA_HISTORY.FECHA) = '2015')
-- and DATA_HISTORY.RASCLIENTID in ('70606')   
--                                                   UNION ALL 
--                                                   SELECT     (dbo.DATA_HISTORY.TASA_OCUPACION) 
--FROM         dbo.CLIENT_GRUPOS INNER JOIN
--                      dbo.GRUPO ON dbo.CLIENT_GRUPOS.IDGRUPO = dbo.GRUPO.IDGRUPO INNER JOIN
--                      dbo.DATA_HISTORY ON dbo.CLIENT_GRUPOS.IDCENTRO = dbo.DATA_HISTORY.RASCLIENTID
--WHERE     (MONTH(dbo.DATA_HISTORY.FECHA) = '7') AND (YEAR(dbo.DATA_HISTORY.FECHA) = '2015') AND 
--                      (dbo.CLIENT_GRUPOS.IDGRUPO = '1')
--) S)/100) as UDS_VENDIDAS)AS DECIMAL(10, 2)))) AS UDS_VENDIDAS
FROM            dbo.GRUPO INNER JOIN
                         dbo.CLIENT_GRUPOS ON dbo.GRUPO.IDGRUPO = dbo.CLIENT_GRUPOS.IDGRUPO INNER JOIN
                         dbo.DATA_HISTORY ON dbo.CLIENT_GRUPOS.IDCENTRO = dbo.DATA_HISTORY.RASCLIENTID INNER JOIN
                         dbo.CLIENTS ON dbo.CLIENT_GRUPOS.IDCENTRO = dbo.CLIENTS.RASCLIENTID 
GROUP BY dbo.DATA_HISTORY.RASCLIENTID, YEAR(dbo.DATA_HISTORY.FECHA), MONTH(dbo.DATA_HISTORY.FECHA), dbo.CLIENT_GRUPOS.IDGRUPO, dbo.CLIENTS.COMPNAME
HAVING        (dbo.CLIENT_GRUPOS.IDGRUPO = '1') AND (MONTH(dbo.DATA_HISTORY.FECHA) = '7')AND (YEAR(dbo.DATA_HISTORY.FECHA) = '2015')


