

--REPORTE SOLO ADECUADAS SISTEMA TOTAL

SELECT DISTINCT INTERNAL_ID, CENTRAL.FIRST_NAME, CENTRAL.LAST_NAME, CENTRAL.MIDDLE_INITIAL, CENTRAL.DATE_RECEIVED
FROM CENTRAL
WHERE (CENTRAL.INTERNAL_ID LIKE 'A11%') AND CENTRAL.DISPSTS <> 'DBDE' AND STATUS <> 'CANCEL' AND SP_CODE = 676
and INTERNAL_ID NOT in 
 (SELECT distinct SUBSTRING(ORDTASK.FOLDERNO, 1, 10)
FROM         dbo.ORDTASK INNER JOIN
                      dbo.FOLDERS ON dbo.FOLDERS.FOLDERNO = dbo.ORDTASK.FOLDERNO AND dbo.FOLDERS.DEPT = dbo.ORDTASK.DEPT INNER JOIN
                      dbo.CENTRAL ON dbo.CENTRAL.INTERNAL_ID = dbo.FOLDERS.INTERNAL_ID AND 
                      dbo.CENTRAL.DEPT = dbo.FOLDERS.DEPT
WHERE     (dbo.ORDTASK.TS in ('Cancel')) AND (CENTRAL.INTERNAL_ID LIKE 'A11%') and ORDTASK.PAREANTORDNO IS NULL)
AND INTERNAL_ID NOT in 
 (SELECT distinct SUBSTRING(ORDTASK.FOLDERNO, 1, 10)
FROM   ((("CENTRAL" "CENTRAL" LEFT OUTER JOIN "FOLDERS" "FOLDERS" ON ("CENTRAL"."INTERNAL_ID"="FOLDERS"."INTERNAL_ID") AND ("CENTRAL"."DEPT"="FOLDERS"."DEPT")) INNER JOIN "ORDERS" "ORDERS" ON "FOLDERS"."FOLDERNO"="ORDERS"."FOLDERNO") INNER JOIN "RESULTS" "RESULTS" ON "ORDERS"."ORDNO"="RESULTS"."ORDNO") INNER JOIN "ORDTASK" "ORDTASK" ON (("RESULTS"."ORDNO"="ORDTASK"."ORDNO") AND ("RESULTS"."TESTCODE"="ORDTASK"."TESTCODE")) AND ("ORDERS"."ORDNO"="ORDTASK"."ORDNO")
WHERE  ("CENTRAL"."DATE_RECEIVED">=CONVERT(DATETIME, '2018-11-01 00:00:00', 120) AND "CENTRAL"."DATE_RECEIVED"<CONVERT(DATETIME, '2018-11-30 23:59:59', 120)) AND "ORDTASK"."PAREANTORDNO" IS  NULL  AND  NOT ("ORDTASK"."TS"=N'Cancel' OR "ORDTASK"."TS"=N'Draft' OR "ORDTASK"."TS"=N'Prelogged') AND CENTRAL.SP_CODE = 676 and WARNINGFLAG like '%confirma%'
and "ORDTASK"."FOLDERNO" not in 
 (SELECT distinct ORDTASK.FOLDERNO
FROM         dbo.ORDTASK INNER JOIN
                      dbo.FOLDERS ON dbo.FOLDERS.FOLDERNO = dbo.ORDTASK.FOLDERNO AND dbo.FOLDERS.DEPT = dbo.ORDTASK.DEPT INNER JOIN
                      dbo.CENTRAL ON dbo.CENTRAL.INTERNAL_ID = dbo.FOLDERS.INTERNAL_ID AND 
                      dbo.CENTRAL.DEPT = dbo.FOLDERS.DEPT
WHERE     (dbo.ORDTASK.TS in ('Cancel')) AND (CENTRAL.INTERNAL_ID LIKE 'A11%') and ORDTASK.PAREANTORDNO IS NULL))
ORDER BY INTERNAL_ID

--REPORTE SOLO CANCELADAS TOTAL SISTEMA TOTAL
SELECT DISTINCT INTERNAL_ID, CENTRAL.FIRST_NAME, CENTRAL.LAST_NAME, CENTRAL.MIDDLE_INITIAL, CENTRAL.DATE_RECEIVED, STATUS, CENTRAL.RECVCOMMENT
FROM CENTRAL
WHERE (CENTRAL.INTERNAL_ID LIKE 'A11%') AND CENTRAL.DISPSTS <> 'DBDE' AND STATUS = 'CANCEL' AND SP_CODE = 676
ORDER BY INTERNAL_ID

--REPORTE SOLO SEGUIMIENTO
SELECT DISTINCT INTERNAL_ID, CENTRAL.FIRST_NAME, CENTRAL.LAST_NAME, CENTRAL.MIDDLE_INITIAL, CENTRAL.DATE_RECEIVED, STATUS
FROM CENTRAL
WHERE INTERNAL_ID LIKE 'A11%' AND CENTRAL.DISPSTS <> 'DBDE' AND SP_CODE <> 676 AND SP_CODE <> 688
ORDER BY INTERNAL_ID

--REPORTE SOLO SELECTIVAS
SELECT DISTINCT INTERNAL_ID, CENTRAL.FIRST_NAME, CENTRAL.LAST_NAME, CENTRAL.MIDDLE_INITIAL, CENTRAL.DATE_RECEIVED, STATUS
FROM CENTRAL
WHERE INTERNAL_ID LIKE 'A11%' AND CENTRAL.DISPSTS <> 'DBDE' AND SP_CODE <> 676 AND SP_CODE <> 684
ORDER BY INTERNAL_ID

--REPORTE DE INSUFICIENTES Y RECUPERADAS
SELECT DISTINCT "ORDTASK"."ORDNO",  CENTRAL.FIRST_NAME, CENTRAL.LAST_NAME, CENTRAL.MIDDLE_INITIAL, CENTRAL.DATE_RECEIVED, "ORDTASK"."WARNINGFLAG"
FROM   ((("CENTRAL" "CENTRAL" LEFT OUTER JOIN "FOLDERS" "FOLDERS" ON ("CENTRAL"."INTERNAL_ID"="FOLDERS"."INTERNAL_ID") AND ("CENTRAL"."DEPT"="FOLDERS"."DEPT")) INNER JOIN "ORDERS" "ORDERS" ON "FOLDERS"."FOLDERNO"="ORDERS"."FOLDERNO") INNER JOIN "RESULTS" "RESULTS" ON "ORDERS"."ORDNO"="RESULTS"."ORDNO") INNER JOIN "ORDTASK" "ORDTASK" ON (("RESULTS"."ORDNO"="ORDTASK"."ORDNO") AND ("RESULTS"."TESTCODE"="ORDTASK"."TESTCODE")) AND ("ORDERS"."ORDNO"="ORDTASK"."ORDNO")
WHERE  ("CENTRAL"."DATE_RECEIVED">=CONVERT(DATETIME, '2018-11-01 00:00:00', 120) AND "CENTRAL"."DATE_RECEIVED"<CONVERT(DATETIME, '2018-11-30 23:59:59', 120)) AND "ORDTASK"."PAREANTORDNO" IS  NULL  AND  NOT ("ORDTASK"."TS"=N'Cancel' OR "ORDTASK"."TS"=N'Draft' OR "ORDTASK"."TS"=N'Prelogged') AND CENTRAL.SP_CODE = 676
and "ORDTASK"."FOLDERNO" in 
 (SELECT distinct ORDTASK.FOLDERNO
FROM         dbo.ORDTASK INNER JOIN
                      dbo.FOLDERS ON dbo.FOLDERS.FOLDERNO = dbo.ORDTASK.FOLDERNO AND dbo.FOLDERS.DEPT = dbo.ORDTASK.DEPT INNER JOIN
                      dbo.CENTRAL ON dbo.CENTRAL.INTERNAL_ID = dbo.FOLDERS.INTERNAL_ID AND 
                      dbo.CENTRAL.DEPT = dbo.FOLDERS.DEPT
WHERE     (dbo.ORDTASK.TS in ('Cancel')) AND (CENTRAL.INTERNAL_ID LIKE 'A11%') and ORDTASK.PAREANTORDNO IS NULL)
ORDER BY ORDNO

--REPORTE DE CONFIRMACIONES
SELECT DISTINCT "ORDTASK"."ORDNO",  CENTRAL.FIRST_NAME, CENTRAL.LAST_NAME, CENTRAL.MIDDLE_INITIAL, CENTRAL.DATE_RECEIVED, "ORDTASK"."WARNINGFLAG"
FROM   ((("CENTRAL" "CENTRAL" LEFT OUTER JOIN "FOLDERS" "FOLDERS" ON ("CENTRAL"."INTERNAL_ID"="FOLDERS"."INTERNAL_ID") AND ("CENTRAL"."DEPT"="FOLDERS"."DEPT")) INNER JOIN "ORDERS" "ORDERS" ON "FOLDERS"."FOLDERNO"="ORDERS"."FOLDERNO") INNER JOIN "RESULTS" "RESULTS" ON "ORDERS"."ORDNO"="RESULTS"."ORDNO") INNER JOIN "ORDTASK" "ORDTASK" ON (("RESULTS"."ORDNO"="ORDTASK"."ORDNO") AND ("RESULTS"."TESTCODE"="ORDTASK"."TESTCODE")) AND ("ORDERS"."ORDNO"="ORDTASK"."ORDNO")
WHERE  ("CENTRAL"."DATE_RECEIVED">=CONVERT(DATETIME, '2018-11-01 00:00:00', 120) AND "CENTRAL"."DATE_RECEIVED"<CONVERT(DATETIME, '2018-11-30 23:59:59', 120)) AND "ORDTASK"."PAREANTORDNO" IS  NULL  AND  NOT ("ORDTASK"."TS"=N'Cancel' OR "ORDTASK"."TS"=N'Draft' OR "ORDTASK"."TS"=N'Prelogged') AND CENTRAL.SP_CODE = 676 and WARNINGFLAG like '%confirma%'
and "ORDTASK"."FOLDERNO" not in 
 (SELECT distinct ORDTASK.FOLDERNO
FROM         dbo.ORDTASK INNER JOIN
                      dbo.FOLDERS ON dbo.FOLDERS.FOLDERNO = dbo.ORDTASK.FOLDERNO AND dbo.FOLDERS.DEPT = dbo.ORDTASK.DEPT INNER JOIN
                      dbo.CENTRAL ON dbo.CENTRAL.INTERNAL_ID = dbo.FOLDERS.INTERNAL_ID AND 
                      dbo.CENTRAL.DEPT = dbo.FOLDERS.DEPT
WHERE     (dbo.ORDTASK.TS in ('Cancel')) AND (CENTRAL.INTERNAL_ID LIKE 'A11%') and ORDTASK.PAREANTORDNO IS NULL)
ORDER BY ORDNO



-------REPOTES ADICIONALES

--REPORTE TOTAL
SELECT DISTINCT INTERNAL_ID, CENTRAL.FIRST_NAME, CENTRAL.LAST_NAME, CENTRAL.MIDDLE_INITIAL, CENTRAL.DATE_RECEIVED, SP_CODE, STATUS
FROM CENTRAL
WHERE INTERNAL_ID LIKE 'A11%' AND CENTRAL.DISPSTS <> 'DBDE'
ORDER BY INTERNAL_ID

--REPORTE SOLO ADECUADAS SISTEMA TOTAL INCLUYENDO LAS INSUFICIENTES Y RECUPERADAS
SELECT DISTINCT INTERNAL_ID, CENTRAL.FIRST_NAME, CENTRAL.LAST_NAME, CENTRAL.MIDDLE_INITIAL, CENTRAL.DATE_RECEIVED, SP_CODE, STATUS
FROM CENTRAL
WHERE INTERNAL_ID LIKE 'A11%' AND CENTRAL.DISPSTS <> 'DBDE' AND STATUS <> 'CANCEL' AND SP_CODE = 676
ORDER BY INTERNAL_ID

--REPORTE INSUFICIENTES Y RECUPERADAS

SELECT distinct SUBSTRING(ORDTASK.FOLDERNO, 1, 10)
FROM         dbo.ORDTASK INNER JOIN
                      dbo.FOLDERS ON dbo.FOLDERS.FOLDERNO = dbo.ORDTASK.FOLDERNO AND dbo.FOLDERS.DEPT = dbo.ORDTASK.DEPT INNER JOIN
                      dbo.CENTRAL ON dbo.CENTRAL.INTERNAL_ID = dbo.FOLDERS.INTERNAL_ID AND 
                      dbo.CENTRAL.DEPT = dbo.FOLDERS.DEPT
WHERE     (dbo.ORDTASK.TS in ('Cancel')) AND (CENTRAL.INTERNAL_ID like 'R1020%') and ORDTASK.PAREANTORDNO IS NULL

--OTROS

SELECT DISTINCT INTERNAL_ID, CENTRAL.FIRST_NAME, CENTRAL.LAST_NAME, CENTRAL.MIDDLE_INITIAL, CENTRAL.DATE_RECEIVED
FROM CENTRAL
WHERE INTERNAL_ID LIKE 'A11%' AND CENTRAL.DISPSTS <> 'DBDE'
ORDER BY INTERNAL_ID

SELECT *
FROM CENTRAL
WHERE INTERNAL_ID LIKE 'A11%' AND CENTRAL.DISPSTS <> 'DBDE'
ORDER BY INTERNAL_ID




--OTRO REPORTE SOLO ADECUADAS SISTEMA TOTAL CONTABILIZANDO LAS CONFIRMACIONES
SELECT DISTINCT INTERNAL_ID, CENTRAL.FIRST_NAME, CENTRAL.LAST_NAME, CENTRAL.MIDDLE_INITIAL, CENTRAL.DATE_RECEIVED
FROM CENTRAL
WHERE INTERNAL_ID LIKE 'A11%' AND CENTRAL.DISPSTS <> 'DBDE' AND STATUS <> 'CANCEL' AND SP_CODE = 676
and INTERNAL_ID NOT in 
 (SELECT distinct SUBSTRING(ORDTASK.FOLDERNO, 1, 10)
FROM         dbo.ORDTASK INNER JOIN
                      dbo.FOLDERS ON dbo.FOLDERS.FOLDERNO = dbo.ORDTASK.FOLDERNO AND dbo.FOLDERS.DEPT = dbo.ORDTASK.DEPT INNER JOIN
                      dbo.CENTRAL ON dbo.CENTRAL.INTERNAL_ID = dbo.FOLDERS.INTERNAL_ID AND 
                      dbo.CENTRAL.DEPT = dbo.FOLDERS.DEPT
WHERE     (dbo.ORDTASK.TS in ('Cancel')) AND (CENTRAL.INTERNAL_ID like 'R1020%') and ORDTASK.PAREANTORDNO IS NULL)
ORDER BY INTERNAL_ID
